name: Trigger auto deployment for activosficct

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/activosficct-AutoDeployTrigger-e696835a-3a20-4aa2-8e20-5b997dff60f2.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: reginmobiliariadj.azurecr.io
          registryUsername: ${{ secrets.ACTIVOSFICCT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ACTIVOSFICCT_REGISTRY_PASSWORD }}
          containerAppName: activosficct
          resourceGroup: rg-inmobiliaria
          imageToBuild: reginmobiliariadj.azurecr.io/activosficct:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


